--SELECT nombre, apellido rut, edad, genero
--FROM clientes
--WHERE edad> 10 AND genero = 'M'
--ORDER BY edad ASC 




-------------------------- Clase Miercoles-------------
CREATE BIGFILE TABLESPACE tallerbd
DATAFILE 'tallerbd'
SIZE 10M AUTOEXTEND ON;

CREATE USER gaael PROFILE DEFAULT
IDENTIFIED BY admin
DEFAULT TABLESPACE tallerbd;

GRANT CONNECT, resource, CREATE TABLE, debug ANY PROCEDURE,
debug connect SESSION TO gaael;


--
GRANT UNLIMITED TABLESPACE TO gaael;


//-----------------------------------------------------------------------

GRANT CONNECT,  CREATE SESSION, resource, create table, debug any procedure,
debug connect session to gaael;


DROP TABLE EESCUELA_PROCEDENCIA;

CREATE TABLE "EESCUELA_PROCEDENCIA" 
   (	"CVE_ESCUELA" NVARCHAR2(20) NOT NULL ENABLE, 
	"NOMBRE" NVARCHAR2(200), 
	"NIVEL" NUMBER, 
	"TIPO" NUMBER, 
	"ESTADO" NUMBER NOT NULL ENABLE, 
	"MUNICIPIO" NUMBER, 
	"SERVICIO_EDUCATIVO" NVARCHAR2(100), 
	 CONSTRAINT "PKG_ESCUELAPROC" PRIMARY KEY ("CVE_ESCUELA", "ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TALLERBD"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TALLERBD";

COMMENT ON COLUMN EESCUELA_PROCEDENCIA.NOMBRE IS 'Nombre de la escuela';
COMMENT ON COLUMN EESCUELA_PROCEDENCIA.NIVEL IS '109->secundaria, 102-> bachillerato, nivel Educativo';
COMMENT ON COLUMN EESCUELA_PROCEDENCIA.TIPO IS '1->publico, 2->privado';


LOAD DATA infile "/escproc.csv"  badfile "badfile.txt"  APPEND INTO TABLE gaael.eescuela_procedencia  fields terminated by '|'  OPTIONALLY ENCLOSED BY '"' (CVE_ESCUELA, NOMBRE, NIVEL, TIPO, ESTADO, MUNICIPIO, SERVICIO_EDUCATIVO)